<figure>
  <IMG SRC="../../logo/logo.png" WIDTH=250 ALIGN="right">
</figure>

# IHE Python course, 2017

## Sorting

T.N.Olsthoorn, Feb2017



Sorting (and) filtering are important operations when working with data and databases. This tutorial demonstrates some of the concepts.

The first concept is about `in place` soring versus sorting whereby a new object is generated.

In place sorting does not genrate a new object, hence, no new object is obtained. This is what happens when sorting a list with its methods .sort()

In [12]:
import numpy as np
from numpy import random

In [16]:
myArray = np.random.randint(10, size=15)
print(type(myArray))
print(myArray)

<class 'numpy.ndarray'>
[7 6 4 2 6 3 8 0 2 4 1 4 9 7 0]


By the way, one recognizes an array by the lack of commas between the elements. In a list, these elements are separated by commas. To show this cast the myArray into a list using the `list()` function:

In [18]:
myList = list(myArray)
print(type(myList))
print(myList, "   <---- elements separated by commas !")

<class 'list'>
[7, 6, 4, 2, 6, 3, 8, 0, 2, 4, 1, 4, 9, 7, 0]    <---- elements separated by commas !


Ok, let's sort the array using its metod `sort()` (hence `.sort()`):

In [15]:
newArray =  myArray.sort()
print(newArray)
print(myArray)

None
[0 1 1 3 3 4 5 6 6 6 6 8 8 8 9]


As can be seen newList is None, hence myList.sort() does not generate a list byt the None object.

On the other hand, myList has been sorted, as is shown by print(myList). Obviously, newList is sorted in place.

In place sorting works the same for lists.

In [20]:
print(myList)
newList = myList.sort()
print(newList)
print(myList)

[7, 6, 4, 2, 6, 3, 8, 0, 2, 4, 1, 4, 9, 7, 0]
None
[0, 0, 1, 2, 2, 3, 4, 4, 4, 6, 6, 7, 7, 8, 9]


This shows, that the sort method does not generate a new list, but, on the contrary, the list is sorted `in place`.
Therefore, `assigning myList.sort()` to something else like newList is pointless and, and when done accidentily in code it is confusing, because the result is the object `None` (meaning nothing).

Both numpy arrays and lists have a method sort() that sorts in place. This is possible because both numpy arrays and lists are mutable. If they were not, in place sorting would be impossible. This is the case with tuples, which are immutable

In [22]:
myTuple = tuple(np.random.randint(10, size=15))
print(type(myTuple))
print(myTuple)

<class 'tuple'>
(4, 2, 8, 8, 4, 8, 3, 2, 4, 3, 1, 8, 9, 1, 4)


Sorting the tuple is impossible because an immutable object can't be changed, it can only be replaced.

In [23]:
newTuple = myTuple.sort()

AttributeError: 'tuple' object has no attribute 'sort'

This doesn't work for the reasons given above.

In [24]:
print(type(newTuple))

NameError: name 'newTuple' is not defined

And, of course, if the method .sort() does not exist for tuples, newTuple has not been assigned anything.

There is another function, a builtin function, called `sorted()`. It takes an object like an array, a list, a tuple, a string and generated a new object, which is a sorted copy of the old object. Some examples follow:

In [39]:
myArray = np.random.randint(10, size=15)
myList = list(myArray)
myTuple = tuple(myArray)
myStr = "".join([chr(40 + c) for c in myList])
print(myArray, "                <--- square brackets, no commas (a numpy array)")
print(myList,  "  <--- commas, square brackets (a list)")
print(myTuple, "  <--- commas, parentheses, (a tuple)")
print(myStr, "                                <--- a (somewhat strange) string")

[1 1 7 6 8 6 5 7 2 6 8 4 0 8 4]                 <--- square brackets, no commas (a numpy array)
[1, 1, 7, 6, 8, 6, 5, 7, 2, 6, 8, 4, 0, 8, 4]   <--- commas, square brackets (a list)
(1, 1, 7, 6, 8, 6, 5, 7, 2, 6, 8, 4, 0, 8, 4)   <--- commas, parentheses, (a tuple)
))/.0.-/*.0,(0,                                 <--- a (somewhat strange) string


In [41]:
mA = sorted(myArray)
mL = sorted(myList)
mT = sorted(myTuple)
mS = sorted(myStr)

print(mA)
print(mL)
print(mT)
print(mS)

[0, 1, 1, 2, 4, 4, 5, 6, 6, 6, 7, 7, 8, 8, 8]
[0, 1, 1, 2, 4, 4, 5, 6, 6, 6, 7, 7, 8, 8, 8]
[0, 1, 1, 2, 4, 4, 5, 6, 6, 6, 7, 7, 8, 8, 8]
['(', ')', ')', '*', ',', ',', '-', '.', '.', '.', '/', '/', '0', '0', '0']


First of all, sorted produces a new object in all cases.

Also, whatever the sorted object was, the outcome is a list (square brackets and commas). This is true for the numpy array `myArray`, the list `myList` and the tuple `myTuple` and even for the string `myStr`.

So if you and the original object types back you should cast them (that is explicitly do it yourself) like so:

In [44]:
type( np.array(mA))
type( list(mL))
type( tuple(mT))
type( "".join(mS))

print( np.array(mA))
print( list(mL))
print( tuple(mT))
print( "".join(mS))

[0 1 1 2 4 4 5 6 6 6 7 7 8 8 8]
[0, 1, 1, 2, 4, 4, 5, 6, 6, 6, 7, 7, 8, 8, 8]
(0, 1, 1, 2, 4, 4, 5, 6, 6, 6, 7, 7, 8, 8, 8)
())*,,-...//000


You can't sort a dict and you can't sort a set. This is because both have not order.

In [46]:
{1: 'a', 2:'b', 3:'c'}.sort()   # trying to sort a dict : impossible, no method .sort()

AttributeError: 'dict' object has no attribute 'sort'

In [49]:
sorted({3: 'a', 1:'b', 2:'c'})   # trying to sort a dict using sorted

[1, 2, 3]

In this case the keys of the dict are put in a list and sorted. The values are not touched or involved at all.

Now let's create a dict with arbitrary keys, of different types (tuples, string, numbers). These keys are all immutable, for otherwise they cannot function as keys in a dict:

In [58]:
myDict = {(3, 2) : 'a', 'abcd' : 'dog', (4, 'abc') : ['dog', 5]}
print(myDict)
print(myDict.keys())
print(myDict.values())

{(3, 2): 'a', (4, 'abc'): ['dog', 5], 'abcd': 'dog'}
dict_keys([(3, 2), (4, 'abc'), 'abcd'])
dict_values(['a', ['dog', 5], 'dog'])


Next try to sort this dict, like with did before with the previous dict:

In [57]:
sorted(myDict)  # doesn't work, because, python doen't know how to sort such diverse keys

TypeError: unorderable types: str() < tuple()

It didn't work because the keys are not sortable. There is not obvious way to sort combinations of numbers, strings and tuples.

Next see what happens when we try to sort a set. A set is created by a list of objects between braces.

In [47]:
{'a', 'a', 'b', 3, 'c', 'b'}

{'a', 'b', 3, 'c'}

A set only holds the unique elements.

In [60]:
{'a', 'a', 'b', 3, 'c', 'b'}.sort()  # does not work, see the error message

AttributeError: 'set' object has no attribute 'sort'

A set obviously does not have a method sort() because there is not order in the elements of a set. Therefore, in place sorting does not make sense.

Take attention in the error message, which shows that the object has not attribute 'sort'. Learn to intepret Python's error messages.

In [51]:
sorted({'a', 'a', 'b', 3, 'c', 'b'})  # doesn't work.

TypeError: unorderable types: int() < str()

Look at the eror message, it's a Type error, the keys that are a combination of whole numbers (ints) and strings can not be sorted together because there's no order defined. This is what the error message conveys.

In [59]:
sorted({3, 1, 4, 2, 3, 1})  # This works, becaus the elements (not the set) are sortable.

[1, 2, 3, 4]

As we saw, `sorted()` generates a list. In this case it puts the elements of the set in a list and sorts it. Sorted() always generates a new list object.

Sorted has more potential inputs, which we can see by typing

```sorted?```

in a new cell and execute it.

This is then shown in a new window at the bottom of the screen:

>Signature: `sorted(iterable, key=None, reverse=False)`
>Docstring:
>Return a new list containing all items from the iterable in ascending order.
>
>A custom key function can be supplied to customise the sort order, and the
>reverse flag can be set to request the result in descending order.
>Type:      builtin_function_or_method

Obviously, `revere=True` sorts in descending manner

But `key` is special and our next subject.

`key` expects a function as value. `key` is needed when sorting complex items for which where is no obvious way to sort them. Let's assume that we have a list of tuples such as 3D coordinates:

In [67]:
myList = [(4, 3, 5), (6, -1, 7), (4, 1, 2), (-2, 3, -4), (3, 5, 0)]
sorted(myList)

[(-2, 3, -4), (3, 5, 0), (4, 1, 2), (4, 3, 5), (6, -1, 7)]

As is seen, these tuples are sorted based on their first value [-2, 3, 4, 6] and on their second value for itmes for which the first are the same and so on. But what if we want to sort them base on their third value instead?

In that case, we need a function that decides which of two itmes (here tuples) is smallest. In this case the function, given a tuple should just return the third element of it for  coparison. This looks like so:

In [71]:
def comp(tpl):
    return tpl[2]

sorted(myList, key=comp)

[(-2, 3, -4), (3, 5, 0), (4, 1, 2), (4, 3, 5), (6, -1, 7)]

The tuples are now sorted according to their third element. Notice that `comp` is a function as can be seen by printing its type

In [72]:
print( type(comp) )

<class 'function'>


Now let's take a dict of animals each with a dict of their properties

In [75]:
myCircus =   {'duke': {'what': 'horse', 'color': 'brown', 'age':7, 'weight': 250},
              'spooky': {'what': 'cat', 'color': 'orange', 'age':9, 'weight': 2.3},
              'mooh': {'what': 'cow', 'color': 'black-white}', 'age':4, 'weight': 290},
              'john': {'what': 'elephant', 'color': 'grey', 'age': 22, 'weight': 1840}}

In [76]:
myCircus['john']

{'age': 22, 'color': 'grey', 'weight': 1840, 'what': 'elephant'}

In [78]:
[myCircus['john']['what'], myCircus['john']['age']]

['elephant', 22]

Lets sort these animals, but how. We can sort them based on their age or on their weight. Let's do one after the other

In [84]:
def compAge(animal):
    return animal[1]['age']

sorted([(k, myCircus[k]) for k in myCircus], key=compAge)

[('mooh', {'age': 4, 'color': 'black-white}', 'weight': 290, 'what': 'cow'}),
 ('duke', {'age': 7, 'color': 'brown', 'weight': 250, 'what': 'horse'}),
 ('spooky', {'age': 9, 'color': 'orange', 'weight': 2.3, 'what': 'cat'}),
 ('john', {'age': 22, 'color': 'grey', 'weight': 1840, 'what': 'elephant'})]

This is somewhat complex. The comprehension produces a list with one item per key k. Each item of the list is itself a list of two items, namely the key and the dict [k, myCircus[k]] with the properties of the animal under key k.
The compAge function takes each item, i.e. the list [k, myCircus[k]] (called animal inside the function), it returns animal[1]]['age']. Note that animal[1] is the second item of the incoming list, which is the dict. Therefore, animal[1]['age'] returns the value under key 'age' of the dict belonging to that animal. This value, the age of the animal, is then used to compare the different animals in the list for sorting. That it works is seen on the hand of the increasing ages of the animals in this list.

It's left up to you to sort the animals based on their weight. And yes, sort them in reversed (decreasing order).

if you type
```
myList.sort?
```
you'll see that the sort() method associated to list and to numpy arrays has the same optional arguments as has sorted. So the same rules apply. The only difference is that with the method `myList.sort()`, `myArray.sort()`, the sorting will be done `in place` and no new object is generated.

The other difference is that `sorted()` always creates a list no matter wheather the input is a `numpy array` or a `list`.

Last point, macros, or lambda functions, also called in-line functions or anonymous functions.

You often see them. They are used when defining an extra function is overdone. They can only be use if the function can be defined as a single expression returning a single answer (may be a tuple, list of whatever).

Example:

In [91]:
myfun0 = lambda x: np.sin(x) * np.cos(x)
myfun1 = lambda x, y: np.sin(x) * np.cos(y)
myfun2 = lambda x: x[2]

In [96]:
print( myfun0(2.3),          '<--- sin(x)')
print( myfun1(2.3, 1.5),     '<--- sin(x) * cos(y)')
print( myfun2( (3, 2, -2) ), '             <--- x[2]')

-0.496845501817 <--- $sin(x)$
0.0527490999784 <--- sin(x) * cos(y)
-2              <--- x[2]


We can use these functions anonymously (without giving them a name) for instance for the `key` in the `sorted()` function to get the same result as before, but without having to define an extra function:

In [101]:
sorted([(k, myCircus[k]) for k in myCircus], key=(lambda x: x[1]['age']))

[('mooh', {'age': 4, 'color': 'black-white}', 'weight': 290, 'what': 'cow'}),
 ('duke', {'age': 7, 'color': 'brown', 'weight': 250, 'what': 'horse'}),
 ('spooky', {'age': 9, 'color': 'orange', 'weight': 2.3, 'what': 'cat'}),
 ('john', {'age': 22, 'color': 'grey', 'weight': 1840, 'what': 'elephant'})]

The name `x` in the lambda function is tirvial, it could be anything, like in any function:

In [105]:
sorted([(k, myCircus[k]) for k in myCircus], key=(lambda animal: animal[1]['age']))

[('mooh', {'age': 4, 'color': 'black-white}', 'weight': 290, 'what': 'cow'}),
 ('duke', {'age': 7, 'color': 'brown', 'weight': 250, 'what': 'horse'}),
 ('spooky', {'age': 9, 'color': 'orange', 'weight': 2.3, 'what': 'cat'}),
 ('john', {'age': 22, 'color': 'grey', 'weight': 1840, 'what': 'elephant'})]

If you are a purist, you will have noticed that lambde is in fact not a function, it's a keyword that triggers the generation of a function. Therefor it's

```
lambda x:x[1]['age]
```
or with parentheses:
```
(lamba x:x[1]['age'])
```
and not
```
lambda(x: x[1]['age'])
```

## Using argsort()

`argsort()` is a function in `numpy` and a method of `numpy arrays`. It does not exist as a builtin function like sorted() and it does not exist as a method of `list` like `list.sort()`. What it does, it creates a numpy array with the indices that would sort the original numpy array.

In [125]:
print(myArray)           # prints the original numpy array
print(myArray.argsort()) # print an array of indices that sorts the original array, using the method of myArray
print(np.argsort(myArray)) # same thign, but not we use the function numpy instead of the method of myArray

print("the index array is created")
I = np.argsort(myArray)
print(I)
print("\nThen the array is sorted by picking the values using the generated indices:")
print("Indices     --> " + ("{:3d}" * len(myArray)).format(*[i for i in range(len(myArray))]))
print("myArray     --> " + ("{:3d}" * len(myArray)).format(*myArray))
print("I           --> " + ("{:3d}" * len(I)).format(*I))
print("myArray[I]  --> " + ("{:3d}" * len(myArray)).format(*myArray[I]))

[1 1 7 6 8 6 5 7 2 6 8 4 0 8 4]
[12  0  1  8 11 14  6  3  5  9  2  7  4 10 13]
[12  0  1  8 11 14  6  3  5  9  2  7  4 10 13]
the index array is created
[12  0  1  8 11 14  6  3  5  9  2  7  4 10 13]

Then the array is sorted by picking the values using the generated indices:
Indices     -->   0  1  2  3  4  5  6  7  8  9 10 11 12 13 14
myArray     -->   1  1  7  6  8  6  5  7  2  6  8  4  0  8  4
I           -->  12  0  1  8 11 14  6  3  5  9  2  7  4 10 13
myArray[I]  -->   0  1  1  2  4  4  5  6  6  6  7  7  8  8  8
